name: Bits-2.0
version: 2.1
main: me.koenn.bits.Bits
authors: [Koenn]

commands:
  donate:
    description: "Support the server by donating!"
    aliases: "d"
    usage: "/donate"
  bed:
    description: "Teleport to your bed."
    aliases: "b"
    usage: "/b"
  colorname:
    description: "Set a colored name."
    aliases: "cn"
    usage: "/cn <color>"
  rules:
    description: "See the server rules"
    aliases: "r"
    usage: "/rules"
  beam:
    description: "Beams (teleports) you to a player."
    usage: "/beam <player>"
  warp:
    description: "Warp to a location."
    usage: "/warp <warp>"
  warps:
    description: "View all warps."
    aliases: "ws"
    usage: "/warps"
  delwarp:
    description: "Delete a warp."
    aliases: "dw"
    usage: "/delwarp <player>"
  setwarp:
    description: "Set a new warp."
    aliases: "sw"
    usage: "/setwarp <player>"
  nick:
    description: "Set a custom nickname."
    usage: "/nick <name>"
  whois:
    description: "Get the player behind a nickname."
    usage: "/whois <player>"
  randomteleport:
    description: "Teleports you to a random location."
    aliases: "rtp"
    usage: "/rtp"
  playerhead:
    description: "Gives you a playerhead with a certain name."
    aliases: "ph"
    usage: "/playerhead <player>"
  seen:
    description: "View when a player last played."
    aliases: "s"
    usage: "/s <player>"
  hat:
    description: "Set the item you currently hold as your hat."
    aliases: "h"
    usage: "/hat"
  discord:
    description: "View the discord address."
    usage: "/discord"
  guard:
    description: "Staff only."
    usage: "/guard <set/del> <player>"
  donor:
    description: "Staff only."
    usage: "/donor <set/del> <player>"
  guards:
    description: "View all guards."
    aliases: "gs"
    usage: "/guards"
  donors:
    description: "View all donors."
    aliases: "ds"
    usage: "/donors"
  changelog:
    description: "View the latest changes."
    aliases: "cl"
    usage: "/changelog"
